version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-app
    environment:
      DB_HOST: db 
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      DB_DATABASE: kasir
    depends_on:
      - db 
    ports:
      - "8080:8080"
    command: >
      sh -c "alembic upgrade head &&
             python database/barang_seeder.py &&
             python database/supplier_seeder.py &&
             uvicorn src.main:app --host 0.0.0.0 --port 8080"

  db:
    image: postgres:13  
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kasir  
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"

volumes:
  postgres_data:
